[package]
name = "xot"
version = "0.3.2"
edition = "2021"
license = "MIT"
description = "XML tree library for Rust"
authors = ["Martijn Faassen <faassen@startifact.com>"]
homepage = "https://github.com/faassen/xot"
documentation = "https://docs.rs/xot"
repository = "https://github.com/faassen/xot"
readme = "README.md"
keywords = ["xml", "tree", "dom"]

# XXX we also want to include the examples

[features]
# extra documentation like the tutorial which is in a separate module
# we don't normally want to build
doc = []

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
# cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[dependencies]
ahash = "0.8.2"
indextree = "4.5.0"
vector-map = "1.0.1"
xmlparser = "0.13.5"

[dev-dependencies]
insta = { version = "1.21.2" }
rstest = "0.16.0"
# ensure we run any examples in the tutorial
xot = { path = ".", features = ["doc"]}