[package]
name = "xot"
version = "0.17.0"
edition = "2021"
license = "MIT"
description = "XML tree library for Rust"
authors = ["Martijn Faassen <faassen@startifact.com>"]
homepage = "https://github.com/faassen/xot"
documentation = "https://docs.rs/xot"
repository = "https://github.com/faassen/xot"
readme = "README.md"
keywords = ["xml", "tree", "dom"]

[features]
proptest = ["dep:proptest"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ahash = "0.8.2"
indextree = "4.5.0"
xmlparser = "0.13.5"
proptest = { version = "1.0.0", optional = true }
next-gen = "0.1.1"
encoding_rs = "0.8.33"
xhtmlchardet = "2.2.0"
vecmap-rs = "0.2.1"

[dev-dependencies]
insta = { version = "1.21.2" }
rstest = "0.16.0"
proptest = "1.0.0"
